const canvas = document.querySelector('#gameCanvas');
const ctx = canvas.getContext('2d');
const menuView = document.querySelector('#menuView');
const gameView = document.querySelector('#gameView');
const title = document.querySelector('#gameTitle');
const kicker = document.querySelector('#gameKicker');
const hint = document.querySelector('#gameHint');
const W = canvas.width, H = canvas.height;
let activeGame = null, raf = 0, last = 0;
const keys = {};
const pointer = { x: W / 2, y: H / 2, down: false };

document.querySelectorAll('[data-game]').forEach(card => card.addEventListener('click', () => startGame(card.dataset.game)));
document.querySelectorAll('[data-action="menu"]').forEach(button => button.addEventListener('click', showMenu));
document.querySelector('[data-action="sound"]').addEventListener('click', () => {
  const state = document.querySelector('#soundState');
  state.textContent = state.textContent === 'ON' ? 'OFF' : 'ON';
});
document.querySelector('#resetButton').addEventListener('click', () => activeGame?.reset());
window.addEventListener('keydown', event => { keys[event.key.toLowerCase()] = true; if (event.key === 'Escape' && activeGame) showMenu(); if (event.key.toLowerCase() === 'r') activeGame?.reset(); });
window.addEventListener('keyup', event => { keys[event.key.toLowerCase()] = false; });
function locate(event) { const rect = canvas.getBoundingClientRect(); pointer.x = (event.clientX - rect.left) * W / rect.width; pointer.y = (event.clientY - rect.top) * H / rect.height; }
canvas.addEventListener('pointermove', locate);
canvas.addEventListener('pointerdown', event => { locate(event); pointer.down = true; activeGame?.pointerDown(); });
window.addEventListener('pointerup', () => { pointer.down = false; activeGame?.pointerUp(); });
function showMenu() { cancelAnimationFrame(raf); activeGame = null; gameView.classList.add('hidden'); menuView.classList.remove('hidden'); document.querySelector('#statusText').textContent = 'ARCADE ONLINE'; }
function startGame(name) { cancelAnimationFrame(raf); activeGame = name === 'cat' ? new CatGame() : new BearGame(); menuView.classList.add('hidden'); gameView.classList.remove('hidden'); title.textContent = name === 'cat' ? 'Stretchy Cat Rap' : 'Cursor Bear'; kicker.textContent = name === 'cat' ? 'A SPRINGY MUSIC TOY' : 'A WEATHER SURVIVAL GAME'; document.querySelector('#statusText').textContent = 'PLAYING'; hint.textContent = name === 'cat' ? 'DRAG EITHER END OF THE CAT' : 'KEEP THE BEAR AWAY FROM THE BOLT'; hint.classList.remove('fade'); setTimeout(() => hint.classList.add('fade'), 3500); last = performance.now(); loop(last); }
function loop(now) { if (!activeGame) return; const dt = Math.min((now - last) / 1000, .033); last = now; activeGame.update(dt, now / 1000); activeGame.draw(ctx, now / 1000); raf = requestAnimationFrame(loop); }
function clamp(value, low, high) { return Math.max(low, Math.min(high, value)); }
function vector(x, y) { return { x, y }; }
function distance(a, b) { return Math.hypot(a.x - b.x, a.y - b.y); }
function lerp(a, b, amount) { return vector(a.x + (b.x - a.x) * amount, a.y + (b.y - a.y) * amount); }
function roundedRect(c, x, y, width, height, radius, fill, stroke) { c.beginPath(); c.roundRect(x, y, width, height, radius); if (fill) { c.fillStyle = fill; c.fill(); } if (stroke) { c.strokeStyle = stroke; c.stroke(); } }

class CatGame {
  constructor() { this.reset(); }
  reset() { this.left = vector(330, 355); this.right = vector(670, 355); this.leftVelocity = vector(0, 0); this.rightVelocity = vector(0, 0); this.dragging = null; this.best = 1; }
  pointerDown() { if (distance(pointer, this.left) < 105 || distance(pointer, this.right) < 105) this.dragging = distance(pointer, this.left) < distance(pointer, this.right) ? 'left' : 'right'; }
  pointerUp() { if (this.dragging) { const point = this[this.dragging]; const home = this.dragging === 'left' ? vector(330, 355) : vector(670, 355); const velocity = this[`${this.dragging}Velocity`]; velocity.x += (home.x - point.x) * 2.5; velocity.y += (home.y - point.y) * 2.5; } this.dragging = null; }
  update(dt) { for (const [name, home] of [['left', vector(330, 355)], ['right', vector(670, 355)]]) { const point = this[name]; const velocity = this[`${name}Velocity`]; if (this.dragging === name) { point.x = clamp(pointer.x, 70, 930); point.y = clamp(pointer.y, 140, 535); velocity.x = velocity.y = 0; } else { velocity.x += (home.x - point.x) * 30 * dt; velocity.y += (home.y - point.y) * 30 * dt; velocity.x *= Math.pow(.84, dt * 60); velocity.y *= Math.pow(.84, dt * 60); point.x += velocity.x * dt; point.y += velocity.y * dt; } } this.best = Math.max(this.best, this.ratio()); }
  ratio() { return distance(this.left, this.right) / 340; }
  draw(c, time) { c.fillStyle = '#272446'; c.fillRect(0, 0, W, H); for (let index = 0; index < 23; index++) { const barHeight = 24 + (Math.sin(time * 5 + index * .7) + 1) * 25; c.fillStyle = `hsl(${260 + index * 3}deg ${35 + index % 4 * 8}% ${35 + index * 2}%)`; c.fillRect(15 + index * 44, H - barHeight, 27, barHeight); } c.fillStyle = '#73e1db'; c.font = '700 43px Space Grotesk'; c.textAlign = 'center'; c.fillText('STRETCHY CAT RAP', W / 2, 65); c.fillStyle = '#fff7ff'; c.font = '600 20px Space Grotesk'; c.fillText('Grab either end • Pull • Release • BOING!', W / 2, 105); c.textAlign = 'left'; c.fillStyle = '#f482a1'; c.font = '700 23px Space Grotesk'; c.fillText(`STRETCH  ${this.ratio().toFixed(2)}x`, 25, 31); c.fillStyle = '#fff7ff'; c.font = '16px DM Mono'; c.fillText(`BEST ${this.best.toFixed(2)}x`, 28, 57); drawCat(c, this.left, this.right, this.dragging); c.textAlign = 'right'; c.fillText('[M] MUSIC  •  [R] RESET  •  [ESC] MENU', W - 20, H - 18); c.textAlign = 'center'; c.fillStyle = '#ffda97'; c.font = '16px DM Mono'; c.fillText(['Pull that cat, let it snap!', 'Long cat groove with a springy back!', 'Stretch left, stretch right!', 'Feline flow all through the night!'][Math.floor(time / 2) % 4], W / 2, H - 51); }
}

function drawCat(c, left, right, dragging) {
  const axis = vector(right.x - left.x, right.y - left.y); const length = Math.max(1, distance(left, right)); const direction = vector(axis.x / length, axis.y / length); const normal = vector(-direction.y, direction.x); const width = clamp(116 / Math.sqrt(Math.max(.6, length / 340)), 70, 135);
  c.fillStyle = '#181329'; c.beginPath(); c.ellipse((left.x + right.x) / 2, Math.max(left.y, right.y) + width * .62, length * .46, 12, 0, 0, Math.PI * 2); c.fill();
  c.strokeStyle = '#e0a459'; c.lineWidth = 22; for (const fraction of [.18, .82]) { const hip = lerp(left, right, fraction); c.beginPath(); c.moveTo(hip.x + normal.x * width * .16, hip.y + normal.y * width * .16); c.lineTo(hip.x + direction.x * (fraction - .5) * 25, hip.y + direction.y * (fraction - .5) * 25 + width * .82); c.stroke(); }
  c.strokeStyle = '#ffda97'; c.lineWidth = width; c.beginPath(); c.moveTo(left.x, left.y); c.lineTo(right.x, right.y); c.stroke(); c.fillStyle = '#ffda97'; c.beginPath(); c.arc(left.x, left.y, width / 2, 0, 7); c.arc(right.x, right.y, width / 2, 0, 7); c.fill();
  c.strokeStyle = '#e0a459'; c.lineWidth = Math.max(7, width / 12); for (const fraction of [.3, .47, .64]) { const point = lerp(left, right, fraction); c.beginPath(); c.moveTo(point.x - normal.x * width * .46, point.y - normal.y * width * .46); c.lineTo(point.x - normal.x * width * .15, point.y - normal.y * width * .15); c.stroke(); }
  const head = vector(right.x + direction.x * width * .16, right.y + direction.y * width * .16); c.fillStyle = '#ffda97'; c.beginPath(); c.arc(head.x, head.y, width * .56, 0, 7); c.fill(); c.fillStyle = '#e0a459'; for (const sign of [-1, 1]) { c.beginPath(); c.moveTo(head.x - direction.x * width * .55 + normal.x * sign * width * .4, head.y - direction.y * width * .55 + normal.y * sign * width * .4); c.lineTo(head.x - direction.x * width * .05 + normal.x * sign * width * .28, head.y - direction.y * width * .05 + normal.y * sign * width * .28); c.lineTo(head.x - direction.x * width * .05 - normal.x * sign * width * .2, head.y - direction.y * width * .05 - normal.y * sign * width * .2); c.fill(); }
  c.fillStyle = '#302238'; for (const sign of [-1, 1]) { c.beginPath(); c.arc(head.x + direction.x * width * .2 + normal.x * sign * width * .2, head.y + direction.y * width * .2 + normal.y * sign * width * .2, 5, 0, 7); c.fill(); } c.fillStyle = '#f482a1'; c.beginPath(); c.arc(head.x + direction.x * width * .42, head.y + direction.y * width * .42, 7, 0, 7); c.fill();
  if (dragging) { const held = dragging === 'left' ? left : right; c.strokeStyle = '#73e1db'; c.lineWidth = 4; c.beginPath(); c.arc(held.x, held.y, width / 2 + 13, 0, 7); c.stroke(); }
}

class BearGame {
  constructor() { this.image = new Image(); this.image.src = 'bear/bear.jpg'; this.reset(); }
  reset() { this.bear = vector(W / 2, 300); this.velocity = vector(0, 0); this.day = 0; this.elapsed = 0; this.nextStrike = 2.7 + Math.random() * 1.3; this.strike = 0; this.shock = 0; this.targetX = W / 2; this.over = false; this.won = false; }
  update(dt, time) { if (this.over || this.won) return; this.elapsed += dt; this.day = Math.min(6, Math.floor(this.elapsed / 6)); if (this.day === 4 && this.strike <= 0) this.nextStrike -= dt; if (this.nextStrike <= 0) { this.strike = 1.6; this.nextStrike = 7 + Math.random() * 4; } if (this.strike > 0) { this.strike -= dt; if (this.strike < .35 && Math.abs(this.bear.x - this.targetX) < 70) this.over = true; } if (this.elapsed > 8 && this.shock <= 0) this.shock = 2.3; if (this.shock > 0) this.shock -= dt; const wind = vector((keys.a ? -1 : 0) + (keys.d ? 1 : 0), (keys.w ? -1 : 0) + (keys.s ? 1 : 0)); this.velocity.x += (pointer.x - this.bear.x) * 4 * dt + wind.x * 35 * dt; this.velocity.y += (pointer.y - this.bear.y) * 4 * dt + wind.y * 35 * dt + 1600 * dt; this.velocity.x *= .985; this.velocity.y *= .985; this.bear.x += this.velocity.x * dt; this.bear.y += this.velocity.y * dt; if (this.bear.y > 570) { this.bear.y = 570; this.velocity.y *= -.18; this.velocity.x *= .86; } this.bear.x = clamp(this.bear.x, 55, 945); if (this.shock <= 0 && Math.random() < dt * .035) this.shock = 2.3; if (this.day === 6) this.won = true; if (this.strike > 0) this.targetX = 500 + Math.sin(time * 1.8) * 360; }
  draw(c, time) { const shake = this.shock > 0 ? vector(Math.sin(time * 49) * 6, Math.sin(time * 67) * 4) : vector(0, 0); c.save(); c.translate(shake.x, shake.y); c.fillStyle = this.strike > 0 ? '#69798d' : '#a5d8e8'; c.fillRect(0, 0, W, H); c.fillStyle = '#67ae69'; c.fillRect(0, 500, W, 150); c.fillStyle = '#42875e'; c.beginPath(); c.arc(220, 540, 280, Math.PI, 7); c.arc(760, 570, 360, Math.PI, 7); c.fill(); c.fillStyle = '#fff'; c.font = '600 17px Space Grotesk'; c.textAlign = 'center'; c.fillText('KEEP THE BEAR MOVING', W / 2, 116); drawDays(c, this.day); if (this.shock > 0) { c.fillStyle = 'rgba(255,255,255,.18)'; c.fillRect(0, 0, W, H); } if (this.strike > 0) { c.strokeStyle = '#fff06a'; c.lineWidth = 12; c.shadowColor = '#fff'; c.shadowBlur = 22; c.beginPath(); c.moveTo(this.targetX, 75); c.lineTo(this.targetX - 35, 190); c.lineTo(this.targetX + 25, 260); c.lineTo(this.targetX - 20, 350); c.lineTo(this.targetX + 10, 500); c.stroke(); c.shadowBlur = 0; } drawBear(c, this.bear, this.image); c.restore(); c.fillStyle = '#17211d'; c.textAlign = 'left'; c.font = '500 16px DM Mono'; c.fillText(`DAY ${['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'][this.day]}`, 25, 625); c.textAlign = 'right'; c.fillText('[WASD] WIND  •  [R] RESET', W - 22, 625); if (this.over || this.won) { c.fillStyle = 'rgba(18,22,31,.83)'; c.fillRect(0, 0, W, H); roundedRect(c, 250, 195, 500, 230, 18, this.won ? '#185b43' : '#281f2a', this.won ? '#8ff09a' : '#ff715b'); c.textAlign = 'center'; c.fillStyle = '#fff'; c.font = '700 57px Space Grotesk'; c.fillText(this.won ? 'YOU WIN!' : 'GAME OVER', 500, 275); c.font = '20px Space Grotesk'; c.fillText(this.won ? 'The bear reached Sunday.' : 'The bear was hit by lightning.', 500, 322); c.font = '500 14px DM Mono'; c.fillText('PRESS R OR USE RESET TO PLAY AGAIN', 500, 375); } }
}

function drawDays(c, active) { const days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']; roundedRect(c, 20, 18, 960, 59, 12, 'rgba(25,35,55,.78)'); days.forEach((day, index) => { const x = 31 + index * 135; roundedRect(c, x, 26, 126, 43, 8, index === active ? '#ffe04e' : '#eff3f5'); c.fillStyle = index === active ? '#17211d' : '#34414b'; c.font = '700 16px Space Grotesk'; c.textAlign = 'center'; c.fillText(day, x + 63, 53); if (index === 4 && index === active) { c.fillStyle = '#8f5c00'; c.font = '10px DM Mono'; c.fillText('THUNDER', x + 63, 65); } }); }
function drawBear(c, point, image) { if (image.complete && image.naturalWidth) { c.drawImage(image, point.x - 62, point.y - 86, 124, 124); return; } c.fillStyle = '#6d4738'; c.beginPath(); c.arc(point.x, point.y, 55, 0, 7); c.fill(); c.fillStyle = '#f8d5a4'; c.beginPath(); c.arc(point.x, point.y + 8, 35, 0, 7); c.fill(); c.fillStyle = '#17211d'; c.beginPath(); c.arc(point.x - 18, point.y - 8, 5, 0, 7); c.arc(point.x + 18, point.y - 8, 5, 0, 7); c.fill(); }